### ISSUE TITLE
DesmuME review

### ISSUE THREAD

**Issue by rico18** [masterfeizz/DeSmuME-Vita#1]
When launching software I was kicked right back of it immediately.

**Comment by masterfeizz** [comment]
Did you place a rom named game.nds on ux0:/data/DeSmuME/  ?

**Comment by gnmmarechal** [comment]
it works fine for me.

**Comment by spiral2k** [comment]
hi thanks for the development, here what i got

slow as fuck
screen is too small

impossible to play

**Comment by gnmmarechal** [comment]
ugh, what do you expect from the first test build of an emulator that was ported from the non-perfect 3DS port, which was ported from the PSP port, which was ported from the PC software?

Give it time.

**Comment by masterfeizz** [comment]
This is a port of the latest version of DeSmuME, it uses some of the modifications used on the 3DS port but it has nothing to do with the PSP. I know the screen is small, but that has been fixed and I will push the changes later today.

**Comment by gnmmarechal** [comment]
Huh, if it uses stuff from the 3DS version, doesn't that mean it uses stuff from the PSP version? IIRC, the 3DS port was ported from the PSP port?

Anyway, gj.

**Comment by masterfeizz** [comment]
It's just a miss understanding since I kept using the 3DeSmuME (unrelated) thread on GBATemp. 3DeSmuME was a port of dsonpsp, but that source was really outdated and mostly broken so I ported the latest version of DeSmuME to the 3DS.

**Comment by gnmmarechal** [comment]
huh, cool. I haven't checked the newer versions, haven't used my 2DS a lot tbh.

**Comment by rico18** [comment]
helps me,  I was kicked out of the application when launching,  I followed instructions as listed

**Comment by rico18** [comment]
Did you place a rom named game.nds ux0:/data/DeSmuME/ ?  (in answer to your question) yes, i did (MasterFizz)

**Comment by rico18** [comment]
can you download a rom and then rename it as game.nds
Because i done that

**Comment by rico18** [comment]
got this working now, thanks, MasterFizz. Only thing is there is no sound, screen is tiny and very slow
