### ISSUE TITLE
Followed directions and still crashing.

### ISSUE THREAD

**Issue by tysonkwsmith** [masterfeizz/DeSmuME-Vita#12]
So I have the shell and have the desmume vpk in a folder and I have gone into the data folder and created a /desmume folder where my roms are located now. I run the vpk package and install it, and once I click on the app bubble in the menu it still just loads up and then goes back to the live tile.

What is going on?

**Comment by masterfeizz** [comment]
There is only one check the emulator does, and it's when it populates the rom list. Make sure your roms are in .nds format and place inside ux0:/data/desmume

**Comment by tysonkwsmith** [comment]
I have done this. They are .nds format and are in the proper folder. I click on the app bubble I click on start and then it just goes back to the live tile

**Comment by tysonkwsmith** [comment]
I did not have them in the folder when I first did this days ago. So I moved them into the proper place and still does not work.

Could it be that I used the shell to move the roms and to create the /desmume folder instead of doing it from file zilla?

**Comment by masterfeizz** [comment]
Doesn't hurt to try

**Comment by Zeroba** [comment]
I'm sure the emu doesn't require it anymore but try changing the name of your game to game.nds

**Comment by masterfeizz** [comment]
It's not required to change the name anymore

**Comment by tysonkwsmith** [comment]
For some reason  it is showing my roms as a .7z file.....just yesterday I looked at them and they were .nds

What's going in here lol

**Comment by masterfeizz** [comment]
You probably didn't extract them

**Comment by tysonkwsmith** [comment]
Just realized that. I have never heard of a .7z file before and while I was looking I  the shell it would show them as .nds files but on the computer there were not unzipped.

Thanks for all you're help.
