### ISSUE TITLE
VHBL 3.68

### ISSUE THREAD

**Issue by SyC06669** [masterfeizz/DeSmuME-Vita#16]
I am running VHBL on FW 3.68. where can I get a compatible install for VHBL to play DS games?

**Comment by masterfeizz** [comment]
VHBL is for launching PSP homebrew on the Vita, this is a native Vita homebrew. This can only be used with henkaku.

**Comment by SyC06669** [comment]
Do you have any suggestions that I can use with vhbl since I can’t run henkaku?

**Comment by masterfeizz** [comment]
DSonPSP is the only option, albeit not a useful one.
