### ISSUE TITLE
second intial test

### ISSUE THREAD

**Issue by rico18** [masterfeizz/DeSmuME-Vita#2]
Desmume emulator - runs too slow, which makes it barely playable or enjoyable

**Comment by rico18** [comment]
But other previous issues e.g. small screen were fixed, as they are now adjustable. Also, not to mention there wasn't any audio present.

**Comment by rico18** [comment]
https://www.youtube.com/watch?v=q_r94sQNAtk here's a link of what it could run at please try your best to  optimise the speed and quality

**Comment by rico18** [comment]
keep up the great work :) :+1:

**Comment by Zeroba** [comment]
This is an extremely early port, I don't see this an issue so much as a product of its infancy. 
The vita has much less power than your typical desktop, or even cellphone of today. 
It's going to take a lot of optimization.

**Comment by masterfeizz** [comment]
I'm going to close this since this is not an issue or bug report.
